servers:
- name: domain-a-server3
  adapters:
  - endpoint_ports:
    - Ethernet1
    - Ethernet2
    switch_ports:
    - Ethernet9
    - Ethernet9
    switches:
    - A-LEAF1
    - A-LEAF2
    vlans: '10'
    native_vlan: 4092
    mode: access
    spanning_tree_portfast: edge
    port_channel:
      mode: active
