---

port_profiles:
  - profile: DEFAULT
    spanning_tree_portfast: edge
    mode: access

servers:
  - name: A1
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ A-LEAF1, A-LEAF2 ]
        vlans: 40
        profile: DEFAULT
        port_channel:
          description: A1
          mode: active

  - name: A2
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ A-LEAF1, A-LEAF2 ]
        vlans: 30
        profile: DEFAULT
        port_channel:
          description: A2
          mode: active

  - name: A3
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ A-LEAF3 ]
        vlans: 50
        profile: DEFAULT
        description: A3

  - name: A4
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ A-LEAF3, A-LEAF4 ]
        vlans: 10
        profile: DEFAULT
        port_channel:
          description: A4
          mode: active
        
  - name: A5
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ A-LEAF4 ]
        vlans: 30
        profile: DEFAULT
        description: A5

  - name: A6
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ A-LEAF5, A-LEAF6 ]
        vlans: 70
        profile: DEFAULT
        port_channel:
          description: A6
          mode: active
          
  - name: B1
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ B-LEAF1, B-LEAF2 ]
        profile: DEFAULT
        vlans: 20
        link_tracking:
          enabled: true
          name: CORE-LINKS
        port_channel:
          description: HostG
          mode: active
        ethernet_segment:
          short_esi: 0001:0002:0007

  - name: HostH
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ B-LEAF1, B-LEAF2 ]
        profile: DEFAULT
        vlans: 40
        link_tracking:
          enabled: true
          name: CORE-LINKS
        port_channel:
          description: HostH
          mode: active
        ethernet_segment:
          short_esi: 0001:0002:0008

  - name: HostI
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ B-LEAF3 ]
        profile: DEFAULT
        vlans: 60
        description: HostI
  
  - name: HostJ
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ B-LEAF3, B-LEAF4 ]
        profile: DEFAULT
        vlans: 10
        link_tracking:
          enabled: true
          name: CORE-LINKS
        ethernet_segment:
          short_esi: 0003:0004:0008
        port_channel:
          description: HostJ
          mode: active

  - name: HostK
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ B-LEAF4 ]
        profile: DEFAULT
        vlans: 70
        description: HostK

  - name: HostL
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet3 ]
        switches: [ B-SW1 ]
        profile: DEFAULT
        vlans: 40
        description: HostL
    
  - name: HostM
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet4 ]
        switches: [ B-SW1 ]
        profile: DEFAULT
        vlans: 80
        description: HostM

  - name: HostN
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ C-LEAF1, C-LEAF2 ]
        vlans: 10
        profile: DEFAULT
        port_channel:
          description: HostN
          mode: active

  - name: HostO
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ C-LEAF3 ]
        vlans: 20
        profile: DEFAULT
        description: HostO

  - name: HostP
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ C-LEAF3, C-LEAF4 ]
        vlans: 60
        profile: DEFAULT
        port_channel:
          description: HostP
          mode: active

  - name: HostQ
    adapters:
      - endpoint_ports: [ Ethernet1 ]
        switch_ports: [ Ethernet7 ]
        switches: [ C-LEAF4 ]
        vlans: 50
        profile: DEFAULT
        description: HostQ

  - name: HostR
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ C-LEAF5, C-LEAF6 ]
        vlans: 20
        profile: DEFAULT
        port_channel:
          description: HostR
          mode: active
  
  - name: HostS
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ C-LEAF5, C-LEAF6 ]
        vlans: 60
        profile: DEFAULT
        port_channel:
          description: HostS
          mode: active

network_ports:
  - switches:
      - B-LEAF5
      - B-LEAF6
    switch_ports:
      - Ethernet7
    enabled: true
    mode: trunk
    vlans: "40,80"
    spanning_tree_portfast: edge
    link_tracking:
      enabled: true
      name: CORE-LINKS
    ethernet_segment:
      short_esi: 0005:0006:0007
      redundancy: single-active
      designated_forwarder_algorithm: preference
      designated_forwarder_preferences: 
        - 2000
        - 1000
      dont_preempt: true
    description: AA_TO_B-SW1
