---
- name: Push Configlet
  hosts: act_cv
  connection: local
  gather_facts: no
  vars:
    configlet_list:
      A1_CONFIGLET: "{{ lookup('file', 'templates/test-configlet.txt') }}"
  tasks:
    - name: "Push configlet to CVP"
      tags: [configlet]
      arista.cvp.cv_configlet_v3:
        configlets: "{{configlet_list}}"
        state: present
      register: cvp_configlet

- name: Push Configlet
  hosts: act_cv
  connection: local
  gather_facts: no
  vars:
    CVP_DEVICES:
      - fqdn: A1
        parentContainerName: servers
        configlets:
            - "A1_CONFIGLET"
  tasks:
    - name: "Move device to container and apply configlet"
      tags: [device]
      arista.cvp.cv_device_v3:
        devices: "{{CVP_DEVICES}}"
        state: present
        search_key: fqdn
