---

- name: Configuration deployment
  hosts: DOMAIN_A
  connection: local
  gather_facts: false
  tasks:
    - name: Deploy configurations and tags to CloudVision
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        deploy_to_cv_accept_preview: true
        cv_server: 10.18.130.233
        #cv_token: "{{lookup('file', '../act/act-cv.tok')}}"
        cv_verify_certs: false
