- name: Deploy server configs
  hosts: FABRIC
  connection: local
  gather_facts: false

  vars:
    ansible_user: cvpadmin
    ansible_password: arista123
    ansible_network_os: arista.eos.eos
    ansible_ssh_pass: arista123
    ansible_connection: network_cli
    ansible_become: true
    ansible_become_method: enable

  tasks:

    - name: Gather only the config and default facts for {{ inventory_hostname }}
      arista.eos.eos_facts:
        gather_network_resources:
          - interfaces
          - l2_interfaces
          - lag_interfaces
      register: network_resources_result_A
    
    - name: Gather only the config and default facts for {{ inventory_hostname }}
      arista.eos.eos_facts:
        gather_network_resources:
          - interfaces
          - l2_interfaces
          - lag_interfaces
      register: network_resources_result_B
      
    - name: Save {{ inventory_hostname }} facts to file
      copy:
        content: "{{ network_resources_result_A | to_nice_yaml(indent=2) }}"
        dest: /tmp/network_resources_result_A.yml
    
    - name: Save {{ inventory_hostname }} facts to file
      copy:
        content: "{{ network_resources_result_B | to_nice_yaml(indent=2) }}"
        dest: /tmp/network_resources_result_B.yml
    
    - name: Run parsing script
      command: python scripts/eos-to-yaml_v2.py
      register: parse_output
