---

- name: Deploy server configs
  hosts: SERVERS
  connection: local
  gather_facts: false
  vars:
      # EOS Configuration Directory name
    output_dir_name: 'servers'
    output_dir: '{{ root_dir }}/{{ output_dir_name }}'

  tasks:
        
    - name: build servers
      tags: [build]
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen
      
    - name: Deploy configurations and tags to CloudVision
      tags: [deploy]
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        deploy_to_cv_accept_preview: true
        cv_server: 10.18.160.209
        cv_token: "{{lookup('file', '../act/act-cv.tok')}}"
        cv_verify_certs: false
        
