---
- name: Validate Network State
  hosts: DOMAIN_A
  connection: httpapi
  gather_facts: false
    
  tasks:

    - name: Validate
      ansible.builtin.import_role:
        name: arista.avd.eos_validate_state
      vars:
        use_anta: true
        save_catalog: true
        skip_tests:
          - category: AvdTestHardware
