---

  name: "Build and push fabric configs to cv"
  
  on:
    push:
      branches-ignore:
        - main
      paths:
        - 'tech-library/datacenter/**/host_vars/**'
        - 'tech-library/datacenter/**/group_vars/**'
  jobs:
    build-configs:
      runs-on: self-hosted
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'

        - name: Install Ansible and AVD roles 
          run: |
            pip install "pyavd[ansible]"
            ansible-galaxy collection install arista.avd
        
        - name: Build and Deploy to CV
          run: |
            cd tech-library/datacenter/
            python build.py
            ansible-playbook playbooks/deploy.yml

        - name: 'Upload Artifact'
          uses: actions/upload-artifact@v4
          with:
            name: build-fabric-artifact
            path: tech-library/datacenter/intended/**
            retention-days: 1
  
