---

  name: "Build AVD configs"
  
  on:
    push:
      branches-ignore:
        - main
      paths:
        - 'tech-library/datacenter/**/host_vars/**'
        - 'tech-library/datacenter/**/group_vars/**'
  jobs:
    build-configs:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: 3.11.7
            cache: 'pip'
        - run: pip install -r requirements.txt
        - run: |
            cd tech-library/datacenter/
            python build.py

        - name: 'Upload Artifact'
          uses: actions/upload-artifact@v4
          with:
            name: build-fabric-artifact
            path: intended/**
            retention-days: 1
  