name: Validate and Merge

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Branch to validate and potentially merge"
        required: true
      merge_confirmation:
        description: "Confirmation to merge branch after validation (yes/no)"
        required: false
        default: "no"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Ansible and AVD roles
        run: |
          pip install "pyavd[ansible]"
          ansible-galaxy collection install arista.avd

      - name: Run AVD validate_state role
        run: |
          ansible-playbook playbooks/validate.yml \
            -e branch=${{ github.event.inputs.environment }}

      - name: Validation Result
        if: success()
        run: echo "Validation succeeded for branch: ${{ github.event.inputs.environment }}"

  merge:
    needs: validate
    if: ${{ github.event.inputs.merge_confirmation == 'yes' && success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge branch into main
        run: |
          git checkout main
          git merge origin/${{ github.event.inputs.environment }}
          git push origin main

      - name: Merge Success
        run: echo "Branch ${{ github.event.inputs.environment }} merged into main."
